### ISSUE TITLE
Support for multiple URL parameters in dev proxy

### ISSUE THREAD

**Issue by azappa** [lusentis/dawson#23]
When setting an api route cannot access to all parameters but only the first.
Something like
```javascript
service.api = {
  path: '{lang}/services/{service}',
};
```
doesn't catch `{service}` param in event.

**Comment by lusentis** [comment]
Multiple parameters are supported by dawson (cloudformation, apigateway etc...) but not by the development proxy. We need to update it asap.

**Comment by lusentis** [comment]
fixed in f11dbf4
